```{r}
PbP.GSW <- subset(PbP, team=="GSW")

ev <- c("ejection","end of period","jump ball",
        "start of period","unknown","violation",
        "timeout","sub","foul","turnover")

event.unsel <- which(PbP.GSW$event_type %in% ev)
PbP.GSW.ev <- PbP.GSW[-event.unsel,]

attach(PbP.GSW.ev)
T <- table(oppTeam, event_type, exclude=ev)
detach(PbP.GSW.ev)
```

```{r}
library(dplyr)
library(lsr)
library(tibble)
FF <- fourfactors(Tbox, Obox)
attach(Tbox)
attach(FF)
X <- data.frame(PTS, P2M, P3M, FTM, REB=OREB+DREB, AST,
                STL, BLK, ORtg, DRtg)
detach(Tbox)
detach(FF)
Playoff <- Tadd$Playoff
eta <- sapply(X, function(Y){
  cm <- round(tapply(Y, Playoff, mean), 1)
  eta2 <- etaSquared(aov(Y~Playoff))[1]*100
  c(cm, round(eta2, 2))
}) %>%
  t() %>%
  as.data.frame() %>%
  rename(No=N, Yes=Y, eta2=V3) %>%
  rownames_to_column('rownm') %>%
  arrange(-eta2) %>%
  column_to_rownames('rownm')
```
```{r}
data <- subset(Pbox, MIN>=500)
attach(data)
X <- data.frame(AST, TOV)/MIN
detach(data)
cor(X$AST, X$TOV)
cor(rank(X$AST), rank(X$TOV))
cor(X$AST, X$TOV, method="spearman")
cor(X)
```
```{r}
# 3.2 analysing pairwise correlations
data <- merge(Pbox, Tadd, by="Team")
data <- subset(data, MIN>=500)
# Per minute measurements
attach(data)
X <- data.frame(PTS, P3M, P2M, REB=(OREB+DREB), AST,
                TOV, STL, BLK)/MIN
detach(data)
```



```{r}
# Correlation plot
corrmatrix <- corranalysis(X[,1:8], threshold=0.5)
plot(corrmatrix)
```
```{r}
# Add playoff info plus the scatter plot
X <- data.frame(X, Playoff=data['Playoff'])
scatterplot(X, data.var=1:8, z.var="Playoff",
            diag=list(continuous="blankDiag"))
```
```{r}
# The dimensionality reduction
attach(Pbox)
data <- data.frame(PTS, P3M, P2M, REB=OREB+DREB,
                   AST, TOV, STL, BLK)
detach(Pbox)
data <- subset(data, Pbox$MIN>=1500)
id <- Pbox$Player[Pbox$MIN>=1500]

mds <- MDSmap(data)
plot(mds, labels=id)
```
```{r}
selp <- which(id=="Al Horford" | id=="Kyle Korver" |
                id=="Myles Turner" | id=="Kyle Kuzma" |
                id=="Andrew Wiggins")
plot(mds, labels=id, subset=selp, col.subset="tomato")
plot(mds, labels=id, subset=selp, col.subset="tomato",
     zoom=c(0,3,0,2))
plot(mds, z.var=c("P2M","P3M","AST","REB"),
     level.plot=FALSE, palette=topo.colors)
```

```{r}
# Network analysis with assistnet
PbP.GSW <- subset(PbP, team=="GSW")
netdata <- assistnet(PbP.GSW)
set.seed(7)
plot(netdata)
```
```{r}
# Same without Draymond
cols <- paste0(c("a","h"), rep(1:5,each=2))
PbP.GSW.DG0 <- PbP.GSW[!apply(PbP.GSW[,cols], 1, "%in%",
                              x="Draymond Green"),]
netdata.DG0 <- assistnet(PbP.GSW.DG0)
set.seed(1)
plot(netdata.DG0)
```

```{r}
# More netdata analysis
TAB <- netdata$assistTable
X <- netdata$nodeStats
names(X)[1] <- "Player"
data <- merge(X, Pbox, by="Player")
mypal <- colorRampPalette(c("blue","yellow","red"))
scatterplot(data, data.var=c("FGM","FGM_ASTp"),
            z.var="MIN", labels=data$Player,
            palette=mypal, repel_labels=TRUE)
```
```{r}
# Inequality analysis in assists
# First select average of 1 quarter per game
sel <- which(data$MIN>984)
tab <- TAB[sel,sel]

no.pl <- nrow(tab)
pR <- pM <- vector(no.pl, mode="list")
GiniM <- array(NA, no.pl)
GiniR <- array(NA, no.pl)
for (pl in 1:no.pl) {
  ineqplM <- inequality(tab[pl,], npl=no.pl)
  GiniM[pl] <- ineqplM$Gini
  ineqplR <- inequality(tab[,pl], npl=no.pl)
  GiniR[pl] <- ineqplR$Gini
  title <- rownames(tab)[pl]
  pM[[pl]] <- plot(ineqplM, title=title)
  pR[[pl]] <- plot(ineqplR, title=title)
}
# arrange plots
library(gridExtra)
grid.arrange(grobs=pM, nrow=2)
grid.arrange(grobs=pR, nrow=2)

# Inequality bubble plot showing association between made and recieved
XX <- data.frame(X[sel,], GiniM, GiniR)
labs <- c("Gini Index for assists made",
          "Gini Index for assists received",
          "Assists received", "Assists made")
bubbleplot(XX, id="Player", x="GiniM", y="GiniR",
           col="FGM_AST", size="AST",
           labels=labs, text.size=4)
```

```{r}
# Network analysis
library(tidygraph)
library(igraph)
library(CINNA)

net1 <- as_tbl_graph(netdata$assistNet)
class(net1) <- "igraph"
centr_degree(net1)
alpha_centrality(net1)
closeness(net1, mode="all")
betweenness(net1)
calculate_centralities(net1)
```

```{r}

```

